CREATE TABLE `product` (
  `product_id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) DEFAULT NULL,
  `color` varchar(20) DEFAULT NULL,
  `status_id` int(11) DEFAULT 0,
  `product_type_id` int(11) DEFAULT 0,
  `category_id` int(11) DEFAULT NULL,
  `size` int(11) DEFAULT NULL,
  `sku` varchar(20) DEFAULT NULL,
  `condition_id` int(11) DEFAULT NULL,
  `weight` decimal(19,2) DEFAULT NULL,
  `notes` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`product_id`),
  UNIQUE KEY `product_id_UNIQUE` (`product_id`),
  KEY `fk_status_id_idx` (`status_id`),
  KEY `fk_product_type_id_idx` (`product_type_id`),
  KEY `fk_condition_id_idx` (`condition_id`),
  CONSTRAINT `fk_condition_id` FOREIGN KEY (`condition_id`) REFERENCES `product_condition` (`product_condition_id`),
  CONSTRAINT `fk_product_type_id` FOREIGN KEY (`product_type_id`) REFERENCES `product_type` (`product_type_id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_status_id` FOREIGN KEY (`status_id`) REFERENCES `status` (`status_id`)
) ENGINE=InnoDB AUTO_INCREMENT=199401 DEFAULT CHARSET=utf8mb4